// examples/react-19-typescript/src/App.tsx
import React, { useState } from 'react';
import Rollbar from 'rollbar';
import ErrorBoundary from './ErrorBoundary';
import TestError from './TestError';

function App() {
  const [rollbar] = useState(() => new Rollbar({
    accessToken: 'POST_CLIENT_ITEM_TOKEN',
    captureUncaught: true,
    captureUnhandledRejections: true,
  }));

  const logInfo = () => {
    // Example log event using the rollbar object.
    rollbar.info('react test log');
  };

  const throwError = () => {
    // Example error, which will be reported to rollbar.
    throw new Error('react test error');
  };

  return (
    <React.Fragment>
      <h1>Rollbar Example for React</h1>
      <button id="rollbar-info" onClick={logInfo}>
        Log Info
      </button>
      <button id="throw-error" onClick={throwError}>
        ThrowError
      </button>
      <ErrorBoundary rollbar={rollbar}>
        <TestError />
      </ErrorBoundary>
    </React.Fragment>
  );
}

export default App;

// examples/angular2/src/app/app.component.ts
import { Component, Inject, NgZone } from '@angular/core';
import { RollbarService } from './rollbar';
import * as Rollbar from 'rollbar';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor(
    @Inject(RollbarService) private rollbar: Rollbar,
    private ngZone: NgZone,
  ) {
    // Used by rollbar.js tests
    window['angularAppComponent'] = this;
  }

  // Example log event using the rollbar object.
  rollbarInfo() {
    this.rollbar.info('angular test log');
  }

  // Example error, which will be reported to rollbar.
  throwError() {
    throw new Error('angular test error');
  }

  // Example log event with undefined arg.
  rollbarInfoWithUndefined() {
    this.rollbar.info('angular test log with undefined', undefined);
  }
  // Methods used by rollbar.js tests

  publicRollbarInfo() {
    this.ngZone.run(() => this.rollbarInfo());
  }

  publicThrowError() {
    this.ngZone.run(() => this.throwError());
  }

  publicRollbarInfoWithUndefined() {
    this.ngZone.run(() => this.rollbarInfoWithUndefined());
  }

  doCheckCount: number = 0;

  // Used to monitor change detection events
  ngDoCheck() {
    this.doCheckCount += 1;
  }
}
