// examples/react-19-js-components/src/App.js
import React, { useState } from 'react';
import Rollbar from './rollbar';
import './App.css';

function App() {
  const [rollbar] = useState(() => new Rollbar({
    accessToken: 'POST_CLIENT_ITEM_TOKEN',
    captureUncaught: true,
    captureUnhandledRejections: true,
  }));

  const logInfo = () => {
    // Example log event using the rollbar object.
    rollbar.info('react test log');
  };

  const throwError = () => {
    // Example error, which will be reported to rollbar.
    throw new Error('react test error');
  };

  return (
    <React.Fragment>
      <h1>Rollbar Example for React</h1>
      <button id="rollbar-info" onClick={logInfo}>
        Log Info
      </button>
      <button id="throw-error" onClick={throwError}>
        ThrowError
      </button>
    </React.Fragment>
  );
}

export default App;

// sdks/rollbar.js/examples/angular2/src/app/app.component.ts
import { Component, Inject, NgZone } from '@angular/core';
import { RollbarService } from './rollbar';
import * as Rollbar from 'rollbar';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(@Inject(RollbarService) private rollbar: Rollbar, private ngZone: NgZone) {
    // Used by rollbar.js tests
    window['angularAppComponent'] = this;
  }

  // Example log event using the rollbar object.
  rollbarInfo() {
    this.rollbar.info('angular test log');
  }

  // Example error, which will be reported to rollbar.
  throwError() {
    throw new Error('angular test error');
  }

  // Methods used by rollbar.js tests

  publicRollbarInfo() {
    this.ngZone.run(() => this.rollbarInfo());
  }

  publicThrowError() {
    this.ngZone.run(() => this.throwError());
  }

  doCheckCount: number = 0;

  // Used to monitor change detection events
  ngDoCheck() {
    this.doCheckCount += 1;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Rollbar example for Angular 2+
  </h1>
</div>
<button id="rollbar-info" (click)="rollbarInfo()">Log info</button>
<button id="throw-error" (click)="throwError()">Throw Error</button>

<router-outlet></router-outlet>
